services:
  - type: web
    name: linear-regression-api
    env: python
    plan: free
    region: oregon
    pythonVersion: "3.11"
    buildCommand: "python3 -m pip install --upgrade pip setuptools wheel && python3 -m pip install -r API/requirements.txt"
    startCommand: "uvicorn API.main:app --host 0.0.0.0 --port $PORT"